const STATUS = {
  CALL_INITIATED: "CALL_INITIATED",
  CALL_EXISTS: "CALL_EXISTS",
  COLLISION: "COLLISION_DETECTED",
  CALL_CANCELLED: "CALL_CANCELLED",
  CALL_NOT_FOUND: "CALL_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

module.exports = STATUS;
